_wandb:
    value:
        cli_version: 0.21.0
        e:
            z1cl3vh4ion5nm8xw29f73qbnd77i7e4:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Unknown
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236859412480"
                email: rish030798@gmail.com
                executable: /Users/rishabhkumar/miniconda3/envs/bci_env/bin/python
                git:
                    commit: 59a42db7ed98bc0ed88906366434234afef3e2a5
                    remote: https://github.com/KumarRishabh/Kernel-Experiments.git
                host: Rishabhs-MacBook-Air-5.local
                memory:
                    total: "8589934592"
                os: macOS-15.5-arm64-i386-64bit
                program: <python with no main file>
                python: CPython 3.10.8
                root: /Users/rishabhkumar/Kernel-Experiments/betaprime-experiments
                startedAt: "2025-07-15T13:58:47.229984Z"
                writerId: z1cl3vh4ion5nm8xw29f73qbnd77i7e4
        m: []
        python_version: 3.10.8
        t:
            "3":
                - 2
            "4": 3.10.8
            "5": 0.21.0
            "8":
                - 2
            "12": 0.21.0
            "13": darwin-arm64
